DROP TABLE IF EXISTS TBL_USERS;

CREATE TABLE TBL_USERS (
  id INT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  user_name VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  create_timestamp TIMESTAMP DEFAULT NULL,
  update_timestamp TIMESTAMP DEFAULT NULL,
  role VARCHAR(50) DEFAULT 'ADMIN'
);

CREATE SEQUENCE USER_SEQ;